http:
  routers:
    api:
      rule: Host(`elma-assist.de`) && PathPrefix(`/api`)
      service: api
      entryPoints: [websecure]
    livekit:
      rule: Host(`rtc.elma-assist.de`)
      service: livekit
      entryPoints: [websecure]
    files:
      rule: Host(`files.elma-assist.de`)
      service: files
      entryPoints: [websecure]
    web:
      rule: Host(`elma-assist.de`) && (Path(`/app`) || PathPrefix(`/app/`) || PathPrefix(`/_next/`) || Path(`/widget`) || PathPrefix(`/widget/`) || PathPrefix(`/a/`) || Path(`/s`) || PathPrefix(`/s/`))
      service: web
      entryPoints: [websecure]
    landing:
      rule: Host(`elma-assist.de`)
      service: landing
      entryPoints: [websecure]
  services:
    api: {loadBalancer: {servers: [{url: "http://api:8000"}]}}
    livekit: {loadBalancer: {servers: [{url: "http://livekit:7880"}]}}
    files: {loadBalancer: {servers: [{url: "http://seaweedfs:8333"}]}}
    web: {loadBalancer: {servers: [{url: "http://web:3000"}]}}
    landing: {loadBalancer: {servers: [{url: "http://landing:80"}]}}
